version: '2'

services:
    php:
        build: .
        ports:
            - 9000:80
        links:
            - mysql:mysql
               
    mysql:
        build: ./.docker/mysql/
        ports:
            - 3306:3306

        volumes:
          - /var/lib/mysql